writing_task:
  description: >
    Create a professional LinkedIn post based on the {content_plan}. 
    Writing Guidelines:
    - Search online what natural human writing looks like and apply that style
    Format requirements:
    - No hashtags
    - No emojis
    Writing style:
    - Aim for a conversational tone
  expected_output: >
    Deliver a cohesive, professional LinkedIn post
  agent: content_writer

editing_task:
  description: >
    Review and refine the LinkedIn post to ensure it meets the highest standards.
    Ensure the final post:
    - Contains no hashtags
    - Contains no emojis
    - Sounds like a human wrote it
    Tone check:
    - Remove any AI-like patterns
    - remove any wording that is typical for LLMs
  expected_output: >
    Provide a polished LinkedIn post.
  agent: editor
