writing_task:
  description: >
    Create a professional LinkedIn post based on the provided content plan. Transform the research insights into 
    a compelling, authoritative narrative that delivers clear value to a professional audience.
    Writing Guidelines:
    1. Professional Structure
       - Begin with a clear, compelling opening that establishes expertise
       - Present the main insight with authority and precision
       - Support with concrete evidence and professional experience
       - Conclude with actionable takeaways or thought-provoking insights
    2. Content Quality
       - Focus on depth over surface-level observations
       - Maintain consistent professional tone throughout
       - Balance technical accuracy with accessibility
       - Incorporate relevant industry context and implications
    3. Engagement Approach
       - Foster meaningful professional discussion
       - Include thoughtful questions that prompt expert insights
       - Reference industry trends and developments
       - Create natural opportunities for knowledge sharing
    Content to Create: {post}
  expected_output: >
    Deliver a cohesive, professional LinkedIn post that:
    - Demonstrates thought leadership
    - Provides substantial industry insights
    - Maintains consistent professional tone
    - Encourages meaningful professional dialogue
    - Adheres to LinkedIn's length guidelines
    - Uses strategic but minimal formatting for readability
  agent: content_writer

editing_task:
  description: >
    Review and refine the LinkedIn post to ensure it meets the highest standards of professional communication
    while maximizing engagement potential.
    Focus Areas:
    1. Content Quality
       - Clarity and precision of message
       - Logical flow and argumentation
       - Technical accuracy and credibility
       - Professional tone consistency
    2. Structure Optimization
       - Clear paragraph progression
       - Effective use of white space
       - Strategic placement of key points
       - Natural content flow
    3. Professional Standards
       - Industry-appropriate terminology
       - Citation of credible sources
       - Balanced perspective
       - Authority establishment
    4. Engagement Elements
       - Professional discussion prompts
       - Knowledge-sharing opportunities
       - Industry relevance
       - Call to professional action
    Content to Edit: {post}
  expected_output: >
    Provide a polished LinkedIn post that:
    - Demonstrates clear thought leadership
    - Maintains consistent professional tone
    - Presents ideas with clarity and authority
    - Encourages meaningful professional dialogue
    - Optimizes readability through clean formatting
  agent: editor
