writing_task:
  description: >
    Create engaging LinkedIn content for {topic} based on the provided research and your existing knowledge. 
    The content should follow LinkedIn best practices, be concise yet valuable, and maintain professional tone.

    Content to Create: {post}
  expected_output: >
    A well-crafted LinkedIn post that effectively communicates key insights about {topic}. The content should be:
    - Built on strong, valuable base content
    - Formatted for optimal LinkedIn engagement (using line breaks, emojis where appropriate)
    - Written in a professional yet conversational tone
    - Include hooks
    - Stay within LinkedIn's optimal character limits
    - Use bullet points or numbered lists for better readability
    - Include thought-provoking questions or insights to encourage engagement

    Provide only the content, no additional notes or explanations.
  agent: content_writer

editing_task:
  description: >
    Review and optimize the LinkedIn content for {topic}. Ensure it follows platform best practices, maintains professional 
    quality, and maximizes potential engagement. Pay special attention to the strength of the base content, formatting, 
    hooks, and clarity while preserving valuable insights and technical accuracy.

    Content to Edit: {post}
  expected_output: >
    A polished and optimized LinkedIn post that:
    - Has strong, valuable base content
    - Has strong opening hooks
    - Uses effective LinkedIn formatting
    - Maintains professional tone while being engaging
    - Optimizes character count for platform performance
    
    Return only the final content, no editing notes or feedback.
  agent: editor
