writing_task:
  description: >
    Create a professional LinkedIn post based on the {content_plan}. First distill the core insight of the plan core ide and make a comprehensive web search to broaden your understanding of the core idea.
    Then write a professional LinkedIn post. In the post, add a bulleted list of all important key insights.
    Writing Guidelines:
    - No hashtags
    - No emojis
    Writing style:
    - Aim for a conversational tone
  expected_output: >
    Deliver a cohesive, professional LinkedIn post with a bulleted list of all important key insights.
  agent: content_writer

editing_task:
  description: >
    Review and refine the LinkedIn post to ensure it meets the highest standards. 
    Ensure the final post:
    - Contains no hashtags
    - Contains no emojis
    - Sounds like a human wrote it
    - Does not have a call to action
    - Consider if the content could use more research.
    Tone check: if yes make additional research and add the new insights to the post.
    - Remove any AI-like patterns and words that is typical for LLMs
  expected_output: >
    Provide a polished LinkedIn post that is unique, engaging and professional. The post should make the reading of it worth it and create value for the reader.
  agent: editor

