research_task:
  description: >
    Conduct deep, comprehensive research on {topic}. Your investigation should:
    
    UNDERSTAND THE LANDSCAPE
    - Map out the current state of {topic}
    - Identify key players and innovators
    - Uncover major trends and developments
    - Find surprising or counterintuitive insights
    
    GATHER EVIDENCE
    - Find compelling statistics and data points
    - Collect expert quotes and insights
    - Identify relevant case studies
    - Source recent academic research
    
    ANALYZE IMPLICATIONS
    - Examine practical applications
    - Identify common challenges
    - Uncover success factors
    - Spot emerging opportunities
    
    FIND UNIQUE ANGLES
    - Look for underexplored perspectives
    - Identify contrarian viewpoints
    - Spot gaps in common narratives
    - Find unexpected connections

    Focus on depth over breadth. Prioritize quality insights over quantity.
  expected_output: >
    A comprehensive research brief with:
    
    EXECUTIVE SUMMARY
    Key findings and unique angles discovered
    
    CORE INSIGHTS
    Detailed analysis backed by data and expert opinions
    
    PRACTICAL IMPLICATIONS
    Real-world applications and considerations
    
    SUPPORTING EVIDENCE
    All sources, quotes, and statistics properly cited
  agent: researcher

design_task:
  description: >
    Create a strategic content blueprint based on the research. Your design should:
    
    STRUCTURE THE NARRATIVE
    - Design the overall story arc
    - Plan key message placement
    - Map information flow
    - Create engagement points
    
    PLAN CONTENT ELEMENTS
    - Craft headline options
    - Design section flow
    - Plan evidence placement
    - Structure key takeaways
    
    OPTIMIZE FOR ENGAGEMENT
    - Plan hook strategies
    - Design aha-moments
    - Create value-delivery points
    - Structure call-to-actions
    
    Focus on creating a blueprint that guides the writer to create compelling content.
  expected_output: >
    A detailed content blueprint including:
    
    CONTENT STRATEGY
    Overall approach and key messages
    
    DETAILED OUTLINE
    Section-by-section breakdown with specific guidance
    
    ENGAGEMENT ELEMENTS
    Hook strategies and value-delivery points
    
    WRITING GUIDELINES
    Tone, style, and formatting recommendations
  agent: blog_designer

writing_task:
  description: >
    Transform the blueprint and research into engaging content that:
    
    CRAFT THE NARRATIVE
    - Write compelling hooks
    - Develop key arguments
    - Create smooth transitions
    - Build to key takeaways
    
    DELIVER VALUE
    - Present clear insights
    - Support with evidence
    - Provide practical advice
    - Create actionable steps
    
    OPTIMIZE QUALITY
    - Maintain professional tone
    - Ensure readability
    - Polish formatting
    - Check citations
    
    Focus on creating content worth sharing and implementing.
  expected_output: >
    A polished blog post that includes:
    
    ENGAGING INTRODUCTION
    Hook and value proposition
    
    MAIN CONTENT
    Well-structured insights and evidence
    
    PRACTICAL APPLICATION
    Clear takeaways and next steps
    
    PROFESSIONAL FINISH
    Proper formatting and citations
  agent: blog_writer

social_media_task:
  description: >
    Create professional social media content for LinkedIn and Twitter/X that:
    
    LINKEDIN CONTENT
    - Write 3 complete thought leadership posts (1300-2000 characters)
    - Include compelling hooks and insights
    - Add relevant hashtags
    - End with strong call-to-actions
    
    TWITTER CONTENT
    - Create viral-worthy thread (5-7 tweets)
    - Start with powerful hook tweet
    - Break down complex insights
    - Include relevant hashtags
    
    Focus on creating content that drives professional engagement.
  expected_output: >
    A complete social media package with:
    
    LINKEDIN POSTS
    Three distinct, full-length posts ready for publication
    
    TWITTER THREAD
    Complete thread with hook and supporting tweets
    
    HASHTAG SETS
    Strategic hashtags for each platform
  agent: social_media_strategist

review_task:
  description: >
    Transform the content to maximize authenticity and value:
    
    ENHANCE PERSONAL CONNECTION
    - Add authentic personal angles
    - Include relatable examples
    - Share relevant experiences
    - Make insights more actionable
    
    STRENGTHEN ENGAGEMENT
    - Improve story arcs
    - Add emotional hooks
    - Enhance value propositions
    - Strengthen calls for discussion
  expected_output: >
    Final, enhanced versions of:
    
    LINKEDIN CONTENT
    Three optimized posts ready for immediate publication
    
    TWITTER CONTENT
    Polished thread ready for posting
    
    No analysis or explanations - just the improved content.
  agent: content_reviewer
