research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A 2-3 paragraph report summarizing recent advancements, innovations, and key technical details about {topic}. Use bullet points for clarity.
  agent: researcher

analyzing_task:
  description: >
    Research and summarize the impact of this AI topic on various industries, including projected market growth, potential applications, and adoption rates.
  expected_output: >
     A 2-3 paragraph overview highlighting economic impact, industry-specific examples, and market forecasts. Include projected growth and potential sectors for adoption.
  agent: analyst
