research_task:
  description: >
    Conduct deep, comprehensive research on {topic}. Your investigation should:
    
    UNDERSTAND THE LANDSCAPE
    - Map out the current state of {topic}
    - Identify key players and innovators
    - Uncover major trends and developments
    - Find surprising or counterintuitive insights
    
    GATHER EVIDENCE
    - Find compelling statistics and data points
    - Collect expert quotes and insights
    - Identify relevant case studies
    - Source recent academic research
    
    ANALYZE IMPLICATIONS
    - Examine practical applications
    - Identify common challenges
    - Uncover success factors
    - Spot emerging opportunities
    
    FIND UNIQUE ANGLES
    - Look for underexplored perspectives
    - Identify contrarian viewpoints
    - Spot gaps in common narratives
    - Find unexpected connections

    Focus on depth over breadth. Prioritize quality insights over quantity.
  expected_output: >
    A comprehensive research brief with:
    
    EXECUTIVE SUMMARY
    Key findings and unique angles discovered
    
    CORE INSIGHTS
    Detailed analysis backed by data and expert opinions
    
    PRACTICAL IMPLICATIONS
    Real-world applications and considerations
    
    SUPPORTING EVIDENCE
    All sources, quotes, and statistics properly cited
  agent: researcher

social_media_task:
  description: >
    Create professional social media content for LinkedIn and Twitter/X that:
    
    LINKEDIN CONTENT
    - Write 3 complete thought leadership posts (1300-2000 characters)
    - Include compelling hooks and insights
    - Add relevant hashtags
    - End with strong call-to-actions
    
    TWITTER CONTENT
    - Create viral-worthy thread (5-7 tweets)
    - Start with powerful hook tweet
    - Break down complex insights
    - Include relevant hashtags
    
    Focus on creating content that drives professional engagement.
  expected_output: >
    A complete social media package with:
    
    LINKEDIN POSTS
    Three distinct, full-length posts ready for publication
    
    TWITTER THREAD
    Complete thread with hook and supporting tweets
    
    HASHTAG SETS
    Strategic hashtags for each platform
  agent: social_media_strategist

review_task:
  description: >
    Transform the content to maximize authenticity and value:
    
    ENHANCE PERSONAL CONNECTION
    - Add authentic personal angles
    - Include relatable examples
    - Share relevant experiences
    - Make insights more actionable
    
    STRENGTHEN ENGAGEMENT
    - Improve story arcs
    - Add emotional hooks
    - Enhance value propositions
    - Strengthen calls for discussion
  expected_output: >
    Final, enhanced versions of:
    
    LINKEDIN CONTENT
    Three optimized posts ready for immediate publication
    
    TWITTER CONTENT
    Polished thread ready for posting
    
    No analysis or explanations - just the improved content.
  agent: content_reviewer
