research_task:
  description: >
    Conduct thorough, comprehensive detailed and extensive (long) research on {topic}. 
    Focus on finding several unique insights and angles.
  expected_output: >
    A through research on {topic}. The research should be long, detailed and comprehensive.
  agent: researcher

planning_task:
  description: >
    Create 3-5 comprehensive and detailed LinkedIn content plans based on the research_task output. The plan should
    include a comprehensive list of key insights and a bulleted list of most important key insights.
  expected_output: >
    3-5 detailed and comprehensive plans for LinkedIn posts. 
  agent: planner
