research_task:
  description: >
    Conduct thorough research on {topic} and structure your findings into distinct paragraphs.
    For each major point or aspect:
    1. Create a clear title/topic
    2. Write detailed content with facts and insights
    3. Include relevant sources
    4. Ensure each paragraph focuses on a specific aspect
  expected_output: >
    A structured research document with distinct paragraphs, each covering a specific aspect of {topic}.
  agent: researcher

planning_task:
  description: >
    Create 3-5 comprehensive LinkedIn content plans based on the structured research paragraphs.
    Use the research paragraphs to ensure each plan focuses on different aspects and insights.
  expected_output: >
    3-5 detailed and comprehensive plans for LinkedIn posts.
  agent: planner
