research_task:
  description: >
    Conduct thorough research about {topic} using the serper search tool.
    Focus on finding information that would be valuable for creating engaging LinkedIn content.
    Make sure you find any interesting and relevant information given the current year is 2024.
    Search for current trends and discussions in the field, valuable industry insights,
    compelling success stories, relevant statistics, and expert opinions that could
    enrich LinkedIn content. Pay special attention to recent developments and
    discussions that are generating significant engagement among professionals.
  expected_output: >
    A comprehensive research report on {topic} with relevant information that can be transformed
    into compelling LinkedIn content. The report should present key findings and insights,
    highlight trending discussions, include notable statistics, and incorporate expert
    perspectives. All information should be properly referenced with sources clearly cited
    throughout the document.
  agent: researcher

planning_task:
  description: >
    Review the research findings and develop a strategic plan for creating engaging LinkedIn
    content about {topic}. The plan should outline how to present the information in a way
    that resonates with LinkedIn's professional audience. Consider the most impactful way
    to structure the key messages, how to build a compelling narrative flow, and which
    supporting evidence will be most persuasive. Focus on creating content that will
    drive meaningful professional engagement and discussion.
  expected_output: >
    A detailed LinkedIn content plan that outlines content themes and main topics. Each
    section should include a clear subtitle, main message and goal, explanation of why
    it matters to the audience, key supporting points, and referenced sources. The plan
    should provide clear guidance on content presentation and suggest angles for maximum
    engagement on LinkedIn's professional platform.
  agent: planner
