research_task:
  description: >
    Conduct thorough research about {topic} using the serper search tool.
    Focus on finding information that would be valuable for creating engaging LinkedIn content.
    Make sure you find any interesting and relevant information given the current year is 2024.
    Search for current trends and discussions in the field, valuable industry insights,
    compelling success stories, relevant statistics, and expert opinions that could
    enrich LinkedIn content. Pay special attention to recent developments and
    discussions that are generating significant engagement among professionals.
  expected_output: >
    A comprehensive research report on {topic} with relevant information that can be transformed
    into compelling LinkedIn content. The report should present key findings and insights,
    highlight trending discussions, include notable statistics, and incorporate expert
    perspectives. All information should be properly referenced with sources clearly cited
    throughout the document.
  agent: researcher

planning_task:
  description: >
    Review the research findings and develop a strategic plan for creating engaging LinkedIn
    posts about {topic}. Focus on crafting attention-grabbing hooks that immediately draw
    readers in, followed by a clear explanation of why the topic matters to professionals.
    Each post should deliver a specific insight or actionable solution, presented in a
    concise, easy-to-read format. Ensure the content is structured to maintain reader
    interest and encourage engagement while keeping the message focused and digestible.
  expected_output: >
    A detailed plan for 10 LinkedIn posts, where each post includes:
    - An attention-grabbing hook to open with
    - A clear explanation of why the topic matters to the audience
    - A specific insight or actionable solution
    - Key supporting points, presented concisely
    - Suggested formatting for readability (e.g., bullet points, line breaks)
    - Referenced sources
    The plan should prioritize brevity and clarity while maintaining professional value.
  agent: planner
