research_task:
  description: >
    Conduct thorough research on {topic}.
  expected_output: >
    A through research on {topic}.
  agent: researcher

planning_task:
  description: >
    Create a viriety of LinkedIn content plans from the research.
  expected_output: >
    Create a detailed ContentPlan with 3 LinkedInPost objects. 
  agent: planner
