research_task:
  description: >
    Conduct thorough research on {topic}. Focus on finding unique insights, current trends and what is discussed active
    . Try to come up different viewpoints and angles.
  expected_output: >
    A through research on {topic}.
  agent: researcher

planning_task:
  description: >
    Create 10 comprehensive and detailed LinkedIn content plans based on the research_task output.
  expected_output: >
    10 detailed and comprehensive plans for LinkedIn posts. 
  agent: planner
